const DATABASE_NAME = '@smartrestaurant';

//@app:collection

const COLLECTION_PRODUCTS = `${DATABASE_NAME}:product`
const COLLECTION_TOKENS = `${DATABASE_NAME}:token`
const COLLECTION_USERS = `${DATABASE_NAME}:user`

export {
  COLLECTION_PRODUCTS,
  COLLECTION_TOKENS,
  COLLECTION_USERS
}